### PR TITLE
Fix routes defined in main

### LINKED ISSUE #27: Fix endpoints with {id} in path

### PR DESCRIPTION
**Pull request by eau2**

### CODE REVIEW

File: api/src/main/java/ch/heigvd/dai/Main.java [hunk 1]
```diff
@@ -47,15 +47,15 @@ public static void main(String[] args) {
 
     // Users routes
     app.post("/users", usersController::create);
-    app.put("/users", AuthMiddleware.requireAuth(usersController::update));
-    app.delete("/users", AuthMiddleware.requireAuth(usersController::delete));
+    app.put("/users/{id}", AuthMiddleware.requireAuth(usersController::update));
```
Comment (leonardcser) [inline api/src/main/java/ch/heigvd/dai/Main.java]: users do not require as the id is taken from the user token

**Review by leonardcser — CHANGES_REQUESTED** [review]

File: api/src/main/java/ch/heigvd/dai/Main.java [hunk 2]
```diff
@@ -47,15 +47,15 @@ public static void main(String[] args) {
...
+    app.delete("/users/{id}", AuthMiddleware.requireAuth(usersController::delete));
```
Comment (leonardcser) [inline api/src/main/java/ch/heigvd/dai/Main.java]: Same here

**Review by leonardcser — CHANGES_REQUESTED** [review]

**Review by leonardcser — APPROVED** [review]
LGTM
